### ISSUE TITLE
Static IP, connection working but icon on system tray issue.

### ISSUE THREAD

**Issue by hyuma78** [palinek/nm-tray#50]
I'm on lubuntu 20.04LTS. I set a static ip on my eth card and internet works good, but the icon on tray is like in picture:
![screen](https://user-images.githubusercontent.com/27858616/84326935-5516ad80-ab7e-11ea-8769-86ada72ee2d9.jpg)

Why? Is possible to fix it?

**Comment by hmollercl** [comment]
Static you mean no DHCP?

**Comment by hyuma78** [comment]
yes no dhcp, I presume.

**Comment by monetaryabyss** [comment]
@hyuma78 how did you set the static IP. I noticed if you set the IP using the Advanced Network Settings menu that the tray icon works properly. Advanced Network Settings changes networkmanager settings. I also noticed if you set the static IP using netplan the tray icon will show the disconnected state.

**Comment by hyuma78** [comment]
@monetaryabyss I've used the yaml file inside /etc/netplan/
`  GNU nano 4.8                                                                              01-network-manager-all.yaml                                                                                          
# Let NetworkManager manage all devices on this system
#network:
 # version: 2
  #renderer: NetworkManager
network:
  ethernets:
    enp2s0:
      addresses: [192.168.1.108/24]
      gateway4: 192.168.1.1
      nameservers:
        addresses: [1.1.1.1, 1.0.0.1]
  version: 2
`
This is my: 01-network-manager-all.yaml

**Comment by teward** [comment]
This is actually a known issue where you're using **multiple** configuration tools.

When you are using Netplan on a system you CANNOT also configure the interface via NetworkManager.

When you see `renderer: NetworkManager` present in Netplan files, you should ONLY use Network Manager (nm-tray, etc.) to manage your network configs, static or otherwise.  When you also mix in networkd/netplan this will result in dual configuration headaches.

EITHER use NetworkManager (and nm-tray) or netplan.  **Do not mix both.**

(This applies generally for the use of wicd, nm-tray, nm-applet, etc. alongside netplan at the same time - you will get Undefined behavior like this.)

Remove your static config that you set up via Netplan and leave the original NetworkManager config bits uncommented.  THEN configure the static IP via the nm-tray configuration for your ethernet adapter.

nm-tray and Network Manager both *assume* that it has primary control of the interface - and when it doesn't have control of the interface like you're doing, it can't determine connectivity state on it (because it's 'unmanaged' by Network Manager / nm-tray in this setup).

**Comment by hyuma78** [comment]
So how can i fix that?

**Comment by teward** [comment]
> So how can I fix that?

Remove your netplan configuration you added, uncomment the other three lines you commented out in that network configuration file, and use nm-tray and such to configure your ethernet interface, and not netplan.  Reboot after editing your netplan configuration though so the system knows that Network Manager is managing things.

**Comment by hyuma78** [comment]
Ok noe after reboot internet no working anymore. i checked network manager and there is static ip 192.168.1.108
when i try to change netmask with 255.255.255.0 and save settings, on netmask there is only number 25 as the address... this is annoying. gateway is 192.168.1.1

**Comment by teward** [comment]
> netmask 25

Just type `24` in for the netmask - it's using CIDR ranges not old school netmasks.

**Comment by hyuma78** [comment]
> > netmask 25
> 
> Just type `24` in for the netmask - it's using CIDR ranges not old school netmasks.

sorry i miss typed, there is 24... but still the icon have the x and internet no working

**Comment by palinek** [comment]
> This is actually a known issue where you're using multiple configuration tools at once and mixing and matching...

Many thanks @teward for thorough explanation.
